# Generated by Django 5.2.16 on 2026-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('namespace', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('fingerprint_version', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                            ('UNKNOWN', 'Unknown'),
                            ('DEFINITE_FAILURE', 'Definite Failure'),
                        ],
                        max_length=20,
                    ),
                ),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('correlation_id', models.UUIDField()),
                ('claim_token', models.UUIDField(blank=True, default=None, null=True)),
                ('claimed_at', models.DateTimeField()),
                (
                    'in_progress_expires_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ('completed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('unknown_marked_at', models.DateTimeField(blank=True, default=None, null=True)),
                (
                    'unknown_evidence_ref',
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ('resolved_at', models.DateTimeField(blank=True, default=None, null=True)),
                (
                    'resolution_evidence_ref',
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('namespace', 'scope', 'key'), name='idem_uniq_ns_scope_key'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                'status__in',
                                ['IN_PROGRESS', 'COMPLETED', 'UNKNOWN', 'DEFINITE_FAILURE'],
                            )
                        ),
                        name='idem_status_valid',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('status', 'IN_PROGRESS'), _negated=True),
                            models.Q(
                                ('claim_token__isnull', False),
                                ('in_progress_expires_at__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='idem_in_progress_fields',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('status', 'COMPLETED'), _negated=True),
                            models.Q(('result__isnull', False), ('completed_at__isnull', False)),
                            _connector='OR',
                        ),
                        name='idem_completed_fields',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('status', 'UNKNOWN'), _negated=True),
                            models.Q(
                                ('unknown_marked_at__isnull', False),
                                ('unknown_evidence_ref__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='idem_unknown_fields',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('status', 'DEFINITE_FAILURE'), _negated=True),
                            models.Q(
                                ('resolved_at__isnull', False),
                                ('resolution_evidence_ref__isnull', False),
                            ),
                            _connector='OR',
                        ),
                        name='idem_definite_failure_fields',
                    ),
                ],
            },
        ),
    ]
