# Generated by Django 5.2.16 on 2026-07-10 09:28
#
# AuditFact append-only 강제의 DB 계층(R5) — 모델 계층(조회 전용 매니저)이 뚫려도
# raw SQL UPDATE/DELETE를 트리거가 거부한다(SC-005의 "100% 거부"를 문자 그대로 충족).
# 정직한 한정: DB 슈퍼유저의 트리거 제거·DDL은 방어 밖 — 권한 분리는 go-live 전
# 운영 DB 구성의 몫이다(헌장 VI가 규율).

from django.db import migrations, models

_APPEND_ONLY_FORWARD = """
CREATE FUNCTION shared_kernel_auditfact_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'AuditFact is append-only: % is not permitted', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER shared_kernel_auditfact_no_mutate
    BEFORE UPDATE OR DELETE ON shared_kernel_auditfact
    FOR EACH ROW EXECUTE FUNCTION shared_kernel_auditfact_append_only();
"""

_APPEND_ONLY_REVERSE = """
DROP TRIGGER IF EXISTS shared_kernel_auditfact_no_mutate ON shared_kernel_auditfact;
DROP FUNCTION IF EXISTS shared_kernel_auditfact_append_only();
"""


class Migration(migrations.Migration):
    dependencies = [
        ('shared_kernel', '0001_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_id', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=255)),
                ('target_id', models.CharField(max_length=255)),
                ('reason_text', models.TextField()),
                (
                    'reason_code',
                    models.CharField(blank=True, default=None, max_length=100, null=True),
                ),
                ('evidence_ref', models.CharField(max_length=255)),
                ('correlation_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
        migrations.RunSQL(sql=_APPEND_ONLY_FORWARD, reverse_sql=_APPEND_ONLY_REVERSE),
    ]
