# Generated by Django 5.2.16 on 2026-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shared_kernel', '0002_audit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditfact',
            index=models.Index(fields=['correlation_id'], name='shared_kern_correla_2e0fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfact',
            index=models.Index(
                fields=['target_type', 'target_id'], name='shared_kern_target__acffcc_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['correlation_id'], name='shared_kern_correla_44dacb_idx'),
        ),
    ]
